version: 0.0
os: linux 

files:
  - source: /
    destination: /home/ubuntu/Vuejs/
    
hooks:
  BeforeInstall:
    - location: Dependency_Scripts/rmBeforeInstall.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: Dependency_Scripts/startApplication.sh
      timeout: 300
      runas: ubuntu
